version: '2.1'

services:
  wordpress:
    volumes:
      - ../../../../../plugins:/wordpress/plugins
      - ./wp-plugin-studio/custom-modules/phpunit/includes/testers:/wordpress/wp-plugin-studio/custom-modules/phpunit/includes/testers
    build:
      context: .
      args:
        WORDPRESS_DB_PASSWORD: pass
        PHP_IMAGE_TAG: $PHP_IMAGE_TAG
        WORDPRESS_VERSION: $WORDPRESS_VERSION
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mariadb:latest
    restart: always
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=pass --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: pass
